user_skill_level: intermediate
sprint_artifacts: '{project-root}/docs/sprint-artifacts'
project_name: Casa Vistas
tech_docs: '{project-root}/docs'
dev_story_location: '{project-root}/docs/stories'
user_name: JMR
communication_language: English
output_folder: '{project-root}/docs'
bmad_indicator: "ðŸ’Ž [BMAD]"
bmad_folder: .bmad
document_output_language: '{communication_language}'
install_user_docs: true
